# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Firebase Prototype' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Firebase Prototype
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
end
